spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: zrg
    password: zrg123456
    url: 'jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8'
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    view:
      prefix: /
      suffix: .jsp
pagehelper:
  helper-dialect: mysql        
